### PR TITLE
Fix module.xml and cls folder structure

### LINKED ISSUE #1: Make it possible to install through zpm
It would be really great if this could be installed through zpm (or if there were at least instructions on how to install, though it's fairly easy to work out)

### PR DESCRIPTION
**Pull request by isc-tleavitt**
Fixes #1

### CODE REVIEW

**Comment by isc-tleavitt** [comment]
Also, note: it's best from a security perspective to avoid matching roles and just use the current user's actual privileges.

**Comment by SeanConnelly** [comment]
Awesome, thanks. I'm deep in my day work atm, will test in a few hours. Presumably I will just need to use the ZPM command to publish it now?

**Comment by isc-tleavitt** [comment]
@SeanConnelly you can set it up on the Open Exchange to publish when you release, then you can use zpm "install" to pull it in from pm.community.intersystems.com

**Comment by SeanConnelly** [comment]
Thats neat !

**Pull request merged**
